import { NextResponse } from "next/server"; import { z } from "zod"; import { prisma } from "@/lib/db/prisma"; import { requireRole } from "@/lib/auth/authorization"; import { assertSameOrigin } from "@/lib/http/request"; import { jsonError } from "@/lib/http/response";
import { slugify } from "@/lib/services/slug";
const schema=z.object({competitionId:z.string().cuid().nullable().optional(),competitionName:z.string().trim().max(160).nullable().optional(),homeTeamId:z.string().cuid().optional(),awayTeamId:z.string().cuid().optional(),homeTeamName:z.string().trim().min(1).max(160).optional(),awayTeamName:z.string().trim().min(1).max(160).optional(),homeTeamLogoUrl:z.string().trim().max(1000).nullable().optional(),awayTeamLogoUrl:z.string().trim().max(1000).nullable().optional(),kickoffAt:z.coerce.date(),venue:z.string().max(200).nullable().optional(),status:z.enum(["SCHEDULED","POSTPONED","CANCELLED","COMPLETED"]).default("SCHEDULED"),homeScore:z.coerce.number().int().min(0).nullable().optional(),awayScore:z.coerce.number().int().min(0).nullable().optional(),attendance:z.coerce.number().int().min(0).nullable().optional(),matchReport:z.string().max(10000).nullable().optional(),isDemoData:z.boolean().default(false)});

async function resolveNames(data:any){
 const homeName=data.homeTeamName?.trim(); const awayName=data.awayTeamName?.trim();
 if(!homeName||!awayName) return null;
 if(homeName.toLowerCase()===awayName.toLowerCase()) throw new Error("Home and away teams must be different.");
 const resolveTeam=async(name:string,id?:string,logoUrl?:string|null)=>{ if(id){ if(logoUrl!==undefined) await prisma.team.update({where:{id},data:{logoUrl:logoUrl||null}}); return id; } const existing=await prisma.team.findFirst({where:{name:{equals:name,mode:"insensitive"}}}); if(existing){ if(logoUrl!==undefined) await prisma.team.update({where:{id:existing.id},data:{logoUrl:logoUrl||null}}); return existing.id; } const base=slugify(name); let slug=base; for(let i=2;await prisma.team.findUnique({where:{slug},select:{id:true}});i++) slug=`${base}-${i}`; return (await prisma.team.create({data:{name,shortName:name.slice(0,30),slug,isClub:false,isActive:true,logoUrl:logoUrl||null}})).id; };
 const homeTeamId=await resolveTeam(homeName,data.homeTeamId,data.homeTeamLogoUrl); const awayTeamId=await resolveTeam(awayName,data.awayTeamId,data.awayTeamLogoUrl);
 let competitionId=data.competitionId??null; const cname=data.competitionName?.trim(); if(cname){ const existing=await prisma.competition.findFirst({where:{name:{equals:cname,mode:"insensitive"}}}); if(existing) competitionId=existing.id; else { const base=slugify(cname); let slug=base; for(let i=2;await prisma.competition.findUnique({where:{slug},select:{id:true}});i++) slug=`${base}-${i}`; competitionId=(await prisma.competition.create({data:{name:cname,slug,isOfficial:false}})).id; } }
 return {homeTeamId,awayTeamId,competitionId};
}

export async function GET(){const a=await requireRole("ADMIN");if(!a)return jsonError("Administrator access required.",403);const [matches,teams,competitions]=await Promise.all([prisma.fixture.findMany({include:{homeTeam:true,awayTeam:true,competition:true,events:true},orderBy:{kickoffAt:"desc"},take:100}),prisma.team.findMany({orderBy:{name:"asc"}}),prisma.competition.findMany({orderBy:{name:"asc"}})]);return NextResponse.json({matches,teams,competitions});}
export async function POST(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("ADMIN");if(!a)return jsonError("Administrator access required.",403);const p=schema.safeParse(await request.json());if(!p.success)return jsonError("Invalid match data.",422,p.error.flatten());try{const resolved=await resolveNames(p.data);if(!resolved)return jsonError("Home and away team names are required.",422);const {homeTeamName,awayTeamName,homeTeamLogoUrl,awayTeamLogoUrl,competitionName,homeTeamId:_,awayTeamId:__,competitionId:___,...rest}=p.data;return NextResponse.json({match:await prisma.fixture.create({data:{...rest,...resolved},include:{homeTeam:true,awayTeam:true,competition:true}})},{status:201});}catch(err){return jsonError(err instanceof Error?err.message:"Unable to save match.",409);}}
export async function PATCH(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("ADMIN");if(!a)return jsonError("Administrator access required.",403);const id=new URL(request.url).searchParams.get("id");if(!id)return jsonError("Match id is required.",422);const p=schema.partial().safeParse(await request.json());if(!p.success)return jsonError("Invalid match data.",422,p.error.flatten());try{const existing=await prisma.fixture.findUnique({where:{id},include:{homeTeam:true,awayTeam:true,competition:true}});if(!existing)return jsonError("Match not found.",404);const teamOrCompetitionChanged=p.data.homeTeamName!==undefined||p.data.awayTeamName!==undefined||p.data.homeTeamLogoUrl!==undefined||p.data.awayTeamLogoUrl!==undefined||p.data.competitionName!==undefined||p.data.competitionId!==undefined;const resolved=teamOrCompetitionChanged?await resolveNames({homeTeamName:p.data.homeTeamName??existing.homeTeam.name,awayTeamName:p.data.awayTeamName??existing.awayTeam.name,homeTeamId:p.data.homeTeamName!==undefined?p.data.homeTeamId:existing.homeTeamId,awayTeamId:p.data.awayTeamName!==undefined?p.data.awayTeamId:existing.awayTeamId,homeTeamLogoUrl:p.data.homeTeamLogoUrl,awayTeamLogoUrl:p.data.awayTeamLogoUrl,competitionName:p.data.competitionName!==undefined?p.data.competitionName:(existing.competition?.name??null),competitionId:p.data.competitionName!==undefined?p.data.competitionId:existing.competitionId}):{homeTeamId:existing.homeTeamId,awayTeamId:existing.awayTeamId,competitionId:existing.competitionId};if(resolved.homeTeamId===resolved.awayTeamId)return jsonError("Home and away teams must be different.",422);const {homeTeamName,awayTeamName,homeTeamLogoUrl,awayTeamLogoUrl,competitionName,homeTeamId:_,awayTeamId:__,competitionId:___,...rest}=p.data;return NextResponse.json({match:await prisma.fixture.update({where:{id},data:{...rest,...resolved},include:{homeTeam:true,awayTeam:true,competition:true}})});}catch(err){return jsonError(err instanceof Error?err.message:"Unable to update match.",409);}}
export async function DELETE(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("ADMIN");if(!a)return jsonError("Administrator access required.",403);const id=new URL(request.url).searchParams.get("id");if(!id)return jsonError("Match id is required.",422);try{await prisma.fixture.delete({where:{id}});return NextResponse.json({ok:true});}catch{return jsonError("Unable to delete match. Related records may need to be retained.",409);}}
