"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";

type User = { id: string; email: string; firstName: string | null; lastName: string | null; role: string };
export function AccountClient() {
  const [user, setUser] = useState<User | null>(null); const [mode, setMode] = useState<"login" | "register">("login"); const [form, setForm] = useState({ email: "", password: "", firstName: "", lastName: "" }); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const [showPassword, setShowPassword] = useState(false);
  useEffect(() => { fetch("/api/auth/me", { cache: "no-store" }).then(r => r.json()).then(d => setUser(d.user)).finally(() => setLoading(false)); }, []);
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const endpoint = mode === "login" ? "/api/auth/login" : "/api/auth/register"; const body = mode === "login" ? { email: form.email, password: form.password } : form; try { const r = await fetch(endpoint, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) setMessage(d.error ?? "Unable to continue."); else { setUser(d.user); setForm({ email: "", password: "", firstName: "", lastName: "" }); } } catch { setMessage("Unable to connect right now."); } finally { setBusy(false); } }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); setUser(null); }
  if (loading) return <section className="mx-auto max-w-7xl px-5 py-20"><p className="font-bold">Loading account…</p></section>;
  if (user) return <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-black uppercase tracking-[.3em] text-red-600">Account</p><h1 className="mt-3 text-5xl font-black sm:text-7xl">Welcome, {user.firstName || "supporter"}.</h1><p className="mt-5 text-zinc-600">{user.email}</p><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Link href="/shop" className="rounded-3xl bg-zinc-100 p-7"><strong className="text-xl">Shop</strong><span className="mt-2 block text-sm text-zinc-500">Browse the jersey catalogue.</span></Link><Link href="/cart" className="rounded-3xl bg-zinc-100 p-7"><strong className="text-xl">Cart</strong><span className="mt-2 block text-sm text-zinc-500">Review items before checkout.</span></Link><Link href="/account/orders" className="rounded-3xl bg-zinc-100 p-7"><strong className="text-xl">My orders</strong><span className="mt-2 block text-sm text-zinc-500">View order history and status.</span></Link>{(user.role === "ADMIN" || user.role === "SUPER_ADMIN") && <Link href="/admin" className="rounded-3xl bg-black p-7 text-white"><strong className="text-xl">Admin dashboard</strong><span className="mt-2 block text-sm text-white/60">Manage club, commerce and content.</span></Link>}</div><PasswordChange/><button onClick={logout} className="mt-8 rounded-xl border border-zinc-300 px-5 py-3 font-black">Sign out</button></section>;

function PasswordChange(){const [open,setOpen]=useState(false);const [f,setF]=useState({currentPassword:"",newPassword:"",confirmPassword:""});const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMsg("");try{const r=await fetch("/api/auth/password",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(f)});const d=await r.json();setMsg(d.message||d.error||"Unable to change password.");if(r.ok)setF({currentPassword:"",newPassword:"",confirmPassword:""});}catch{setMsg("Unable to connect right now.")}finally{setBusy(false)}}return <div className="mt-8 max-w-xl rounded-3xl border border-zinc-200 p-6"><button type="button" onClick={()=>{setOpen(!open);setMsg("")}} className="flex w-full items-center justify-between text-left"><span><span className="block text-xl font-black">Password & security</span><span className="mt-1 block text-sm text-black/50">Change your account password</span></span><span className="text-sm font-black text-red-600">{open?"Hide":"Change password"}</span></button>{open&&<form onSubmit={submit} className="mt-4 space-y-3"><input required type="password" placeholder="Current password" value={f.currentPassword} onChange={e=>setF({...f,currentPassword:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><input required minLength={8} type="password" placeholder="New password (8+ characters)" value={f.newPassword} onChange={e=>setF({...f,newPassword:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><input required minLength={8} type="password" placeholder="Confirm new password" value={f.confirmPassword} onChange={e=>setF({...f,confirmPassword:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><button disabled={busy} className="rounded-xl bg-red-600 px-5 py-3 font-black text-white">{busy?"Changing…":"Update password"}</button></form>}{msg&&<p className="mt-3 text-sm font-bold">{msg}</p>}</div>}
  return <section className="mx-auto max-w-xl px-5 py-16 lg:px-8"><p className="text-xs font-black uppercase tracking-[.3em] text-red-600">Solmart FC account</p><h1 className="mt-3 text-5xl font-black">{mode === "login" ? "Sign in." : "Create your account."}</h1><p className="mt-4 text-zinc-600">An account is required for the cart and checkout so your orders can be securely associated with you.</p><form onSubmit={submit} className="mt-8 space-y-4">{mode === "register" && <div className="grid gap-4 sm:grid-cols-2"><input required placeholder="First name" value={form.firstName} onChange={e => setForm({...form, firstName:e.target.value})} className="rounded-xl border px-4 py-3" /><input required placeholder="Last name" value={form.lastName} onChange={e => setForm({...form, lastName:e.target.value})} className="rounded-xl border px-4 py-3" /></div>}<input required type="email" placeholder="Email" value={form.email} onChange={e => setForm({...form, email:e.target.value})} className="w-full rounded-xl border px-4 py-3" />
  <div className="relative"><input required type={showPassword ? "text" : "password"} minLength={8} placeholder="Password" value={form.password} onChange={e => setForm({...form, password:e.target.value})} className="w-full rounded-xl border px-4 py-3 pr-12" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3 top-3.5 text-zinc-400 hover:text-black">{showPassword ? <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5"><path strokeLinecap="round" strokeLinejoin="round" d="M3.98 8.223A10.477 10.477 0 0 0 1.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.451 10.451 0 0 1 12 4.5c4.756 0 8.773 3.162 10.065 7.498a10.522 10.522 0 0 1-4.293 5.774M6.228 6.228 3 3m3.228 3.228 3.65 3.65m7.894 7.894L21 21m-3.228-3.228-3.65-3.65m0 0a3 3 0 1 0-4.243-4.243m4.242 4.242L9.88 9.88" /></svg> : <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="h-5 w-5"><path strokeLinecap="round" strokeLinejoin="round" d="M2.036 12.322a1.012 1.012 0 0 1 0-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178Z" /><path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z" /></svg>}</button></div>
  {mode === "login" && <div className="text-right"><Link href="/forgot-password" className="text-sm font-bold text-zinc-500 hover:text-black">Forgot password?</Link></div>}
  <button disabled={busy} className="w-full rounded-xl bg-red-600 px-5 py-4 font-black text-white disabled:opacity-50">{busy ? "Please wait…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{message && <p className="mt-4 rounded-xl bg-red-50 p-4 font-bold text-red-700">{message}</p>}<button onClick={() => { setMode(mode === "login" ? "register" : "login"); setMessage(""); }} className="mt-6 text-sm font-black underline">{mode === "login" ? "Need an account? Register" : "Already have an account? Sign in"}</button></section>;
}
