import { prisma } from "@/lib/db/prisma";
import { SectionHeading } from "@/components/site/section-heading";

export const revalidate = 60;

export default async function ClubPage(){
  const settings=await prisma.siteSetting.findMany({where:{isPublic:true,key:{in:["club_mission","club_vision","club_values","club_history"]}}});
  const map=Object.fromEntries(settings.map(x=>[x.key,x.value]));
  return <div><section className="bg-black px-5 py-20 text-white lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[.3em] text-red-500">The club</p><h1 className="mt-3 max-w-4xl text-5xl font-black tracking-tight sm:text-7xl">A new identity. The same ambition.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Solmart FC is the rebranded identity of a club originally established as KasaCity FC in 2022 and rebranded in 2024.</p></div></section><section className="mx-auto max-w-7xl space-y-16 px-5 py-16 lg:px-8"><SectionHeading eyebrow="History" title="Our story" description={map.club_history||"The club's supplied history begins with KasaCity FC in 2022 and continues with the Solmart FC rebrand in 2024."}/><div className="grid gap-5 md:grid-cols-2"><div className="rounded-3xl bg-zinc-100 p-8"><p className="text-5xl font-black">2022</p><h2 className="mt-4 text-2xl font-black">KasaCity FC</h2><p className="mt-2 text-zinc-600">Original club established.</p></div><div className="rounded-3xl bg-black p-8 text-white"><p className="text-5xl font-black text-red-500">2024</p><h2 className="mt-4 text-2xl font-black">Solmart FC</h2><p className="mt-2 text-white/60">Club rebranded as Solmart FC.</p></div></div><div className="grid gap-6 md:grid-cols-3"><div className="rounded-3xl border border-black/10 p-7"><p className="text-xs font-black uppercase tracking-widest text-red-600">Vision</p><p className="mt-3 text-lg font-bold">{map.club_vision||"Official vision statement coming soon."}</p></div><div className="rounded-3xl border border-black/10 p-7"><p className="text-xs font-black uppercase tracking-widest text-red-600">Mission</p><p className="mt-3 text-lg font-bold">{map.club_mission||"Official mission statement coming soon."}</p></div><div className="rounded-3xl border border-black/10 p-7"><p className="text-xs font-black uppercase tracking-widest text-red-600">Values</p><p className="mt-3 text-lg font-bold whitespace-pre-line">{map.club_values||"Play · Unite · Win."}</p></div></div></section></div>
}
