"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Item = { id: string; quantity: number; variant: { id: string; size: string | null; price: string; salePrice: string | null; stock: number; product: { name: string; images: { url: string; altText: string }[] } } };
export function CartClient() {
  const [items, setItems] = useState<Item[]>([]); const [subtotal, setSubtotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const r = await fetch("/api/cart", { cache: "no-store" }); const d = await r.json(); if (!r.ok) setError(d.error ?? "Unable to load cart."); else { setItems(d.cart.items); setSubtotal(Number(d.subtotal)); } } catch { setError("Unable to load cart."); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function update(itemId: string, quantity: number) { const r = await fetch("/api/cart", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId, quantity }) }); const d = await r.json(); if (!r.ok) { setError(d.error ?? "Unable to update cart."); return; } setItems(d.cart.items); setSubtotal(Number(d.subtotal)); }
  if (loading) return <section className="mx-auto max-w-7xl px-5 py-20"><p className="font-bold">Loading cart…</p></section>;
  return <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-black uppercase tracking-[.3em] text-red-600">Your cart</p><h1 className="mt-3 text-5xl font-black sm:text-7xl">Ready when you are.</h1>{error && <div className="mt-6 rounded-2xl bg-red-50 p-5 font-bold text-red-700">{error} {error.includes("sign in") && <Link href="/account" className="underline">Sign in</Link>}</div>}{!error && !items.length && <div className="mt-10 rounded-3xl bg-zinc-100 p-10"><p className="text-xl font-black">Your cart is empty.</p><Link href="/shop" className="mt-5 inline-block rounded-xl bg-black px-5 py-3 font-black text-white">Shop jerseys</Link></div>}{items.length > 0 && <div className="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]"> <div className="space-y-4">{items.map(item => { const price = Number(item.variant.salePrice ?? item.variant.price); return <article key={item.id} className="flex gap-5 rounded-3xl border border-zinc-200 p-5"><img src={item.variant.product.images[0]?.url || "/images/solmart-fc-logo.png"} alt={item.variant.product.images[0]?.altText || item.variant.product.name} className="h-28 w-28 rounded-2xl bg-zinc-100 object-contain p-3" /><div className="min-w-0 flex-1"><h2 className="text-lg font-black">{item.variant.product.name}</h2><p className="mt-1 text-sm text-zinc-500">Size: {item.variant.size ?? "Standard"}</p><p className="mt-2 font-black">KES {price.toLocaleString()}</p><div className="mt-4 flex items-center gap-2"><button onClick={() => update(item.id, item.quantity - 1)} className="h-9 w-9 rounded-lg border font-black">−</button><span className="w-8 text-center font-black">{item.quantity}</span><button onClick={() => update(item.id, item.quantity + 1)} className="h-9 w-9 rounded-lg border font-black">+</button><button onClick={() => update(item.id, 0)} className="ml-3 text-sm font-black text-red-600">Remove</button></div></div></article> })}</div><aside className="h-fit rounded-3xl bg-zinc-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-[.3em] text-red-500">Summary</p><div className="mt-6 flex justify-between"><span className="text-white/60">Subtotal</span><strong>KES {subtotal.toLocaleString()}</strong></div><div className="mt-3 flex justify-between"><span className="text-white/60">Delivery</span><strong>Calculated at checkout</strong></div><Link href="/checkout" className="mt-7 block rounded-xl bg-red-600 px-5 py-4 text-center font-black hover:bg-white hover:text-black">Proceed to checkout</Link></aside></div>}</section>;
}
