"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
export function CheckoutClient() {
  const [items, setItems] = useState<any[]>([]); const [subtotal, setSubtotal] = useState(0); const [form, setForm] = useState({customerName:"",customerEmail:"",customerPhone:"",deliveryAddress:"",deliveryCity:"Nairobi",deliveryCounty:"Nairobi",notes:""}); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const shipping=300;
  useEffect(()=>{ fetch("/api/cart",{cache:"no-store"}).then(async r=>{const d=await r.json(); if(r.ok){setItems(d.cart.items);setSubtotal(Number(d.subtotal));} else setMessage(d.error||"Please sign in.");}).catch(()=>setMessage("Unable to load your cart.")); },[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();if(!r.ok){setMessage(d.error||"Unable to place order.");}else window.location.href=`/account/orders?created=${encodeURIComponent(d.order.orderNumber)}`;}catch{setMessage("Unable to place order.");}finally{setBusy(false);}}
  if(message && !items.length) return <section className="mx-auto max-w-3xl px-5 py-20"><div className="rounded-3xl bg-zinc-100 p-10"><p className="font-black">{message}</p><Link href="/account" className="mt-5 inline-block text-red-600 underline">Go to account</Link></div></section>;
  return <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><p className="text-xs font-black uppercase tracking-[.3em] text-red-600">Checkout</p><h1 className="mt-3 text-5xl font-black sm:text-7xl">Complete your order.</h1><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_380px]"><form onSubmit={submit} className="space-y-4"><input required placeholder="Full name" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><input required type="email" placeholder="Email" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><input required placeholder="Phone number" value={form.customerPhone} onChange={e=>setForm({...form,customerPhone:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><input required placeholder="Delivery address" value={form.deliveryAddress} onChange={e=>setForm({...form,deliveryAddress:e.target.value})} className="w-full rounded-xl border px-4 py-3"/><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="City" value={form.deliveryCity} onChange={e=>setForm({...form,deliveryCity:e.target.value})} className="rounded-xl border px-4 py-3"/><input placeholder="County" value={form.deliveryCounty} onChange={e=>setForm({...form,deliveryCounty:e.target.value})} className="rounded-xl border px-4 py-3"/></div><textarea placeholder="Order notes (optional)" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="min-h-28 w-full rounded-xl border px-4 py-3"/><p className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-900">Your order will be created first. You will then continue to the Paystack M-PESA payment step to complete your purchase.</p>{message && <p className="rounded-xl bg-red-50 p-4 font-bold text-red-700">{message}</p>}<button disabled={busy} className="w-full rounded-xl bg-red-600 px-5 py-4 font-black text-white disabled:opacity-50">{busy?"Creating order…":"Place order"}</button></form><aside className="h-fit rounded-3xl bg-zinc-950 p-7 text-white"><p className="text-xs font-black uppercase tracking-[.3em] text-red-500">Order summary</p>{items.map(i=><div key={i.id} className="mt-5 flex justify-between gap-4 text-sm"><span>{i.variant.product.name} · {i.variant.size} × {i.quantity}</span><strong>KES {(Number(i.variant.salePrice??i.variant.price)*i.quantity).toLocaleString()}</strong></div>)}<div className="my-6 h-px bg-white/10"/><div className="flex justify-between"><span className="text-white/60">Subtotal</span><strong>KES {subtotal.toLocaleString()}</strong></div><div className="mt-3 flex justify-between"><span className="text-white/60">Delivery</span><strong>KES {shipping.toLocaleString()}</strong></div><div className="mt-5 flex justify-between text-xl"><strong>Total</strong><strong>KES {(subtotal+shipping).toLocaleString()}</strong></div></aside></div></section>;
}
