import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/db/prisma";
import { requireRole } from "@/lib/auth/authorization";
import { assertSameOrigin } from "@/lib/http/request";
import { jsonError } from "@/lib/http/response";
import { hashPassword } from "@/lib/security/password";

const roleSchema=z.object({role:z.enum(["CUSTOMER","ADMIN","SUPER_ADMIN"])});
const createSchema=z.object({email:z.string().email(),firstName:z.string().min(1).max(80),lastName:z.string().min(1).max(80),password:z.string().min(8),role:z.enum(["CUSTOMER","ADMIN","SUPER_ADMIN"])});

export async function GET(){const a=await requireRole("ADMIN");if(!a)return jsonError("Administrator access required.",403);return NextResponse.json({users:await prisma.user.findMany({select:{id:true,email:true,firstName:true,lastName:true,role:true,createdAt:true,_count:{select:{orders:true}}},orderBy:{createdAt:"desc"},take:200})});}
export async function POST(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("SUPER_ADMIN");if(!a)return jsonError("Super administrator access required.",403);const p=createSchema.safeParse(await request.json());if(!p.success)return jsonError("Invalid user details.",422,p.error.flatten());const email=p.data.email.trim().toLowerCase();const exists=await prisma.user.findUnique({where:{email}});if(exists)return jsonError("A user with that email already exists.",409);const user=await prisma.user.create({data:{email,firstName:p.data.firstName.trim(),lastName:p.data.lastName.trim(),passwordHash:await hashPassword(p.data.password),role:p.data.role},select:{id:true,email:true,firstName:true,lastName:true,role:true}});return NextResponse.json({user},{status:201});}
export async function PATCH(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("SUPER_ADMIN");if(!a)return jsonError("Super administrator access required.",403);const id=new URL(request.url).searchParams.get("id");if(!id)return jsonError("User id is required.",422);if(id===a.id)return jsonError("You cannot change your own role.",422);const p=roleSchema.safeParse(await request.json());if(!p.success)return jsonError("Invalid role.",422);return NextResponse.json({user:await prisma.user.update({where:{id},data:{role:p.data.role},select:{id:true,email:true,role:true}})});}

export async function DELETE(request:Request){const e=assertSameOrigin(request);if(e)return e;const a=await requireRole("SUPER_ADMIN");if(!a)return jsonError("Super administrator access required.",403);const id=new URL(request.url).searchParams.get("id");if(!id)return jsonError("User id is required.",422);if(id===a.id)return jsonError("You cannot delete your own account.",422);const target=await prisma.user.findUnique({where:{id},select:{id:true,email:true,role:true,_count:{select:{orders:true}}}});if(!target)return jsonError("User not found.",404);if(target.role==="SUPER_ADMIN"){const count=await prisma.user.count({where:{role:"SUPER_ADMIN"}});if(count<=1)return jsonError("You cannot delete the only SUPER_ADMIN account.",422);}await prisma.$transaction(async(tx)=>{await tx.order.updateMany({where:{userId:id},data:{userId:null}});await tx.user.delete({where:{id}});});return NextResponse.json({message:`User ${target.email} removed. Existing orders were preserved without a user account attached.`});}
